sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2699
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.test.*
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S6478
sonar.issue.ignore.multicriteria.e2.resourceKey=**/features/**
