test:
  myShop:
    ui:
      baseUrl: http://localhost:3111
    api:
      baseUrl: http://localhost:8111
  erp:
    api:
      baseUrl: http://localhost:9111/erp
  clock:
    api:
      baseUrl: none
  tax:
    api:
      baseUrl: http://localhost:9111/tax
