test:
  eshop:
    ui:
      baseUrl: http://localhost:3102
    api:
      baseUrl: http://localhost:8102
  erp:
    api:
      baseUrl: http://localhost:9102/erp
  clock:
    api:
      baseUrl: http://localhost:9102/clock
