services:

  backend:
    image: ghcr.io/optivem/starter/multitier-backend-dotnet:latest
    ports:
      - "8081:8081"
    networks:
      - app-network

  frontend:
    image: ghcr.io/optivem/starter/multitier-frontend-react:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
