name: starter-java-monolith-real

services:

  monolith:
    image: ghcr.io/optivem/starter/monolith-java-monolith:latest
    ports:
      - "2101:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
