name: bump-versions

on:
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Bump Patch Versions
        uses: optivem/actions/bump-patch-versions@v1
        with:
          version-files: |
            VERSION:meta-v,monolith-java-v,monolith-dotnet-v,monolith-typescript-v,multitier-java-v,multitier-dotnet-v,multitier-typescript-v
            system/monolith/dotnet/VERSION:monolith-dotnet-v,meta-v
            system/monolith/java/VERSION:monolith-java-v,meta-v
            system/monolith/typescript/VERSION:monolith-typescript-v,meta-v
            system/multitier/backend-dotnet/VERSION:multitier-backend-dotnet-v,multitier-dotnet-v,meta-v
            system/multitier/backend-java/VERSION:multitier-backend-java-v,multitier-java-v,meta-v
            system/multitier/backend-typescript/VERSION:multitier-backend-typescript-v,multitier-typescript-v,meta-v
            system/multitier/frontend-react/VERSION:multitier-frontend-react-v,multitier-java-v,multitier-dotnet-v,multitier-typescript-v,meta-v
