name: meta-prerelease-stage

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

concurrency:
  group: meta-prerelease-stage
  cancel-in-progress: false

jobs:
  run:
    uses: ./.github/workflows/_meta-prerelease-pipeline.yml
    secrets: inherit
    with:
      level: qa
      variant: all
      skip-local: false
