name: monolith-typescript-verify

on:
  workflow_dispatch:

jobs:
  verify:
    uses: ./.github/workflows/_verify-pipeline.yml
    secrets: inherit
    with:
      prefix: monolith-typescript
      commit-workflows: '["monolith-typescript-commit-stage.yml"]'
