name: monolith-java-verify

on:
  workflow_dispatch:

jobs:
  verify:
    uses: ./.github/workflows/_verify-pipeline.yml
    secrets: inherit
    with:
      prefix: monolith-java
      commit-workflows: '["monolith-java-commit-stage.yml"]'
