name: monolith-typescript-verify

on:
  workflow_dispatch:
    inputs:
      skip-commit-stage:
        description: 'Skip commit stage'
        required: false
        type: boolean
        default: false

jobs:
  verify:
    uses: ./.github/workflows/_verify-pipeline.yml
    secrets: inherit
    with:
      prefix: monolith-typescript
      commit-workflows: '["monolith-typescript-commit-stage.yml"]'
      skip-commit-stage: ${{ inputs.skip-commit-stage == true }}
