name: multitier-system-dotnet-verify

on:
  workflow_dispatch:

jobs:
  verify:
    uses: ./.github/workflows/_verify-pipeline.yml
    secrets: inherit
    with:
      prefix: multitier-system-dotnet
      commit-workflows: '["multitier-backend-dotnet-commit-stage.yml", "multitier-frontend-react-commit-stage.yml"]'
