name: prerelease-pipeline-multitier-dotnet

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Verification level'
        required: false
        type: choice
        options:
          - local
          - commit
          - acceptance
          - qa
        default: 'qa'
      skip-local-stage:
        description: 'Skip local stage'
        required: false
        type: boolean
        default: false
      skip-commit-stage:
        description: 'Skip commit stage'
        required: false
        type: boolean
        default: false

jobs:
  verify:
    uses: ./.github/workflows/_prerelease-pipeline.yml
    secrets: inherit
    with:
      prefix: multitier-dotnet
      architecture: multitier
      language: dotnet
      commit-workflows: '["multitier-backend-dotnet-commit-stage.yml", "multitier-frontend-react-commit-stage.yml"]'
      level: ${{ inputs.level || 'qa' }}
      skip-local-stage: ${{ inputs.skip-local-stage == true }}
      skip-commit-stage: ${{ inputs.skip-commit-stage == true }}
