name: verify-monolith-typescript

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Verification level'
        required: false
        type: choice
        options:
          - local
          - commit
          - acceptance
          - release
        default: 'release'
      skip-local-stage:
        description: 'Skip local stage'
        required: false
        type: boolean
        default: false
      skip-commit-stage:
        description: 'Skip commit stage'
        required: false
        type: boolean
        default: false

jobs:
  verify:
    uses: ./.github/workflows/_verify-pipeline.yml
    secrets: inherit
    with:
      prefix: monolith-typescript
      architecture: monolith
      language: typescript
      commit-workflows: '["monolith-typescript-commit-stage.yml"]'
      level: ${{ inputs.level || 'release' }}
      skip-local-stage: ${{ inputs.skip-local-stage == true }}
      skip-commit-stage: ${{ inputs.skip-commit-stage == true }}
