name: verify-multitier-java

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Verification level'
        required: false
        type: choice
        options:
          - local
          - commit
          - acceptance
          - release
        default: 'release'
      skip-commit-stage:
        description: 'Skip commit stage'
        required: false
        type: boolean
        default: false

jobs:
  verify:
    uses: ./.github/workflows/_verify-pipeline.yml
    secrets: inherit
    with:
      prefix: multitier-java
      architecture: multitier
      language: java
      commit-workflows: '["multitier-backend-java-commit-stage.yml", "multitier-frontend-react-commit-stage.yml"]'
      level: ${{ inputs.level || 'release' }}
      skip-commit-stage: ${{ inputs.skip-commit-stage == true }}
